-- DESTRUCTIVE: erase and rebuild only the EggSort+ application schema.
-- Existing users, egg records, alerts, audit logs, and legacy sales are lost.
-- Supabase Auth/Storage system schemas and their data are not touched.

begin;

drop table if exists public.sale cascade;
drop table if exists public.audit_log cascade;
drop table if exists public.tray_alert cascade;
drop table if exists public.egg_record cascade;
drop table if exists public."user" cascade;

create table public."user" (
  id integer generated by default as identity primary key,
  username varchar(50) not null unique,
  password varchar(200) not null,
  email varchar(254) unique,
  google_sub varchar(255) unique,
  display_name varchar(120),
  avatar_url varchar(1024),
  role varchar(20) not null default 'staff',
  is_active boolean not null default true,
  password_set boolean not null default false,
  invite_token_hash varchar(64),
  invite_expires_at timestamptz
);

create table public.egg_record (
  id integer generated by default as identity primary key,
  weight_grams integer not null,
  size varchar(30) not null,
  quality varchar(30) not null,
  confidence double precision not null default 0.0,
  session_ref varchar(40) not null,
  sorted_at timestamptz not null default now()
);

create table public.tray_alert (
  id integer generated by default as identity primary key,
  tray_number integer not null unique,
  egg_count integer not null,
  session_ref varchar(40) not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.audit_log (
  id integer generated by default as identity primary key,
  event_type varchar(40) not null,
  actor varchar(80) not null default 'System',
  description varchar(300) not null,
  event_key varchar(100) unique,
  created_at timestamptz not null default now()
);

create index ix_egg_record_sorted_at
  on public.egg_record (sorted_at desc);
create index ix_egg_record_size
  on public.egg_record (size);
create index ix_egg_record_quality
  on public.egg_record (quality);
create index ix_tray_alert_is_read
  on public.tray_alert (is_read);
create index ix_audit_log_created_at
  on public.audit_log (created_at desc);

alter table public."user" enable row level security;
alter table public.egg_record enable row level security;
alter table public.tray_alert enable row level security;
alter table public.audit_log enable row level security;

revoke all on table public."user" from anon, authenticated;
revoke all on table public.egg_record from anon, authenticated;
revoke all on table public.tray_alert from anon, authenticated;
revoke all on table public.audit_log from anon, authenticated;

revoke all on sequence public.user_id_seq from anon, authenticated;
revoke all on sequence public.egg_record_id_seq from anon, authenticated;
revoke all on sequence public.tray_alert_id_seq from anon, authenticated;
revoke all on sequence public.audit_log_id_seq from anon, authenticated;

commit;
