-- EggSort+ Supabase schema and RLS policy
-- Paste this entire file into Supabase Dashboard > SQL Editor and Run.
-- The Flask server connects using SUPABASE_DB_URL; browsers must not access
-- these tables through the Supabase Data API.

begin;

create table if not exists public."user" (
  id bigint generated by default as identity primary key,
  username varchar(50) not null unique,
  password varchar(200) not null,
  email varchar(254) unique,
  google_sub varchar(255) unique,
  display_name varchar(120),
  avatar_url varchar(1024),
  role varchar(20) not null default 'staff',
  is_active boolean not null default true,
  password_set boolean not null default false,
  invite_token_hash varchar(64),
  invite_expires_at timestamptz
);

create table if not exists public.egg_record (
  id bigint generated by default as identity primary key,
  weight_grams integer not null,
  size varchar(30) not null,
  quality varchar(30) not null,
  confidence double precision not null default 0.0,
  session_ref varchar(40) not null,
  sorted_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tray_alert (
  id bigint generated by default as identity primary key,
  tray_number integer not null unique,
  egg_count integer not null,
  session_ref varchar(40) not null,
  is_read boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sale (
  id bigint generated by default as identity primary key,
  buyer_name varchar(120) not null,
  size varchar(30) not null,
  quantity integer not null,
  total_amount double precision not null,
  payment_method varchar(30) not null,
  status varchar(30) not null default 'Completed',
  sold_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  event_type varchar(40) not null,
  actor varchar(80) not null default 'System',
  description varchar(300) not null,
  event_key varchar(100) unique,
  created_at timestamptz not null default timezone('utc', now())
);

-- Indexes match the application's dashboards, reports, filtering, and sort
-- operations. Primary-key and unique constraints already create their indexes.
create index if not exists ix_egg_record_sorted_at
  on public.egg_record (sorted_at desc);
create index if not exists ix_egg_record_size
  on public.egg_record (size);
create index if not exists ix_egg_record_quality
  on public.egg_record (quality);
create index if not exists ix_sale_sold_at
  on public.sale (sold_at desc);
create index if not exists ix_sale_status
  on public.sale (status);
create index if not exists ix_tray_alert_is_read
  on public.tray_alert (is_read);
create index if not exists ix_audit_log_created_at
  on public.audit_log (created_at desc);

-- RLS is deliberately deny-by-default. Flask uses the private database URI
-- and performs login/role authorization itself; no browser should use an anon
-- key or authenticated Supabase token to query these tables.
alter table public."user" enable row level security;
alter table public.egg_record enable row level security;
alter table public.tray_alert enable row level security;
alter table public.sale enable row level security;
alter table public.audit_log enable row level security;

revoke all on table public."user" from anon, authenticated;
revoke all on table public.egg_record from anon, authenticated;
revoke all on table public.tray_alert from anon, authenticated;
revoke all on table public.sale from anon, authenticated;
revoke all on table public.audit_log from anon, authenticated;

revoke all on sequence public.user_id_seq from anon, authenticated;
revoke all on sequence public.egg_record_id_seq from anon, authenticated;
revoke all on sequence public.tray_alert_id_seq from anon, authenticated;
revoke all on sequence public.sale_id_seq from anon, authenticated;
revoke all on sequence public.audit_log_id_seq from anon, authenticated;

commit;
