services:
  - type: web
    name: eggsort
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /health
    autoDeployTrigger: commit
